config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/tasks', to: 'tasks#index', as: :tasks
  get '/tasks/new', to: 'tasks#new'
  get 'tasks/:id', to: 'tasks#show', as: :task
  post '/tasks', to: 'tasks#create', as: :tasks_create
  get 'tasks/:id/edit', to: 'tasks#edit', as: :tasks_edit
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<%= @task.inspect %>
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.check_box :completed, class: 'form-control'%>
    Completed
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
<ul>
  <% @tasks.each do |task| %>
    <div class="list-tasks">
      <% if task.completed %>
        <input type="checkbox" checked>
      <% else %>
       <input type="checkbox">
      <% end %>
      <li><%= link_to task.title, task %>
      <%= link_to "Delete", task_path(task),
        method: :delete,
        data: { confirm: "Delete #{task.title}?" } %>
      </li>
    </div>
  <% end %>
</ul>

<div class="list-tasks" >
  <i class="fas fa-plus"></i>
  <%= link_to "Add a new task", tasks_new_path %>
</div>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

<div>
  <%= link_to "Back to list", tasks_path %>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <h1><%= @task.title %></h1>
  <div class="edit-task">
    <i class="fas fa-edit"></i>
    <%= link_to "Edit this task", tasks_edit_path(@task) %>
  </div>
</div>

<p id="task-details"><%= @task.details %></p>

<!-- <div class="task-done-checkbox">
  <input type="checkbox">
  <p>This task is not completed yet</p>
</div> -->

<div class="completed">
  <% if @task.completed %>
    <i class="fa fa-check-square-o padded"><%= ' this task is completed' %></i>
  <% else %>
    <i class="fa fa-square-o padded"><%= ' this task is not completed yet' %></i>
  <% end %>
</div>

<%= link_to "Back to list", tasks_path %>